# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f3ae85b4fb2d12386acc6af4f463fd082d1c91e60a6c667e80b270ab19722dae7e3a1adab9324de9bd0bd5d362973bc753a3ffe002c37b885332427dbbdba78

test:
  secret_key_base: 2bb5410106ac0b94df84326a3201638b52f4d708102ad838d91c5fa1b1f2a8e2899822e9bd943e8331e8909174587fb50452baaccf34f56dc1a8dc6953fffe78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
